# 配置文件

# 数据路径配置
data:
  train_data_path: 'data/raw/train.csv'
  test_data_path: 'data/raw/test.csv'
  processed_train_data: 'data/processed/processed_train.csv'
  processed_test_data: 'data/processed/processed_test.csv'

# 模型参数配置
model:
  input_size: 30            # 输入特征数（根据实际情况修改）
  hidden_sizes: [128, 64]   # 多层隐藏层神经元数
  output_size: 2
  learning_rate: 0.0001     # 调整学习率
  epochs: 10                # 增加训练轮数
  batch_size: 256           # 调整批次大小

# 日志配置文件路径
logging_config: 'config/logging.conf'
