# 配置文件

# 数据路径配置
data:
  train_data_path: 'data/raw/train.csv'
  test_data_path: 'data/raw/test.csv'
  processed_train_data: 'data/processed/processed_train.csv'
  processed_test_data: 'data/processed/processed_test.csv'

# 模型参数配置
model:
  input_size: 24
  hidden_size: 64
  output_size: 2
  learning_rate: 0.001
  epochs: 10
  batch_size: 128

# 日志配置文件路径
logging_config: 'config/logging.conf'

